- name: add ssh key for faculty
  tags: always
  authorized_key:
          user: faculty
          key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAi2z2ojIYgVNxLqwy4SfprnIUfRzGtUjgwlerD2oQZZ ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
          src: "{{ ssh_template_file }}"
          dest: /etc/ssh/sshd_config
          owner: root
          group: root
          mode: 0644
  notify: restart_sshd
